### PR TITLE
Yick

### PR DESCRIPTION
**Pull request by Y1Ck**
Hi all, i have summarized the findings so far this week;
see "week-04-findings.md";
im not comfortable with the findings;
let me know your thoughts;

### CODE REVIEW

**Comment by relientm96** [comment]
We can further update this document too on different thoughts and findings

**Comment by relientm96** [comment]
Actually sorry just a comment from me, is it okay if you put the progress summary directory under the documents folder and recommit?

**Comment by Y1Ck** [comment]
@relientm96 , i have moved it to documents;
let me know if im doing it correctly;

**Comment by nivlekp** [comment]
The documentation looks good. Irrelevant to the content of this pull request, I would suggest squashing the commits into one single commit when merging this. This can be done either on github by selecting the "squash and merge" option, or locally from the command line:

1.  `git log` to see the history
2.  find the hash of the commit before your first commit
3.  git reset <hash> - now you are behind your commits; the changes are still there, but not staged.
4.  now stage your changes, commit and force push

**Pull request merged**
